# Generated by Django 4.0.4 on 2022-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='send_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
