# Generated by Django 4.0.4 on 2022-04-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_sender_chat_second_user_remove_chat_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='second_user',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='first_user',
            new_name='user',
        ),
    ]
