# Generated by Django 4.0.4 on 2022-04-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_rename_second_user_chat_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_current_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_current_message', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
